trigger:
  - master


phases:
  - phase: Test
    queue: Hosted Linux Preview
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6 >= 3.5' 
        addToPath: true 
        architecture: 'x64'

    - script: |
        pip install -r requirements.txt
        pip install -e .
      condition: succeeded()
      displayName: install aztk

    - script: |
        yapf --style .style.yapf -dpr aztk/ aztk_cli/
      condition: succeeded()
      displayName: yapf

    - script: |
        pylint -j 2 -E aztk aztk_cli
      condition: succeeded()
      displayName: pylint
    
    - script: |
        pytest -n 20 --ignore=tests/integration_tests
      condition: succeeded()
      displayName: unit tests

    - script: |
        pytest -n 75
      condition: succeeded()
      displayName: integration tests
